stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - download
    outs:
    - data/raw
  parse:
    cmd: python src/parse.py
    deps:
    - data/raw
    - src/parse.py
    params:
    - parse
    outs:
    - data/parsed
